import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Krystian Szewczyk on 2015-11-11.
 */
public class ProductManager {
    private static Connection conn;
    private String url = "jdbc:hsqldb:hsql://localhost/workdb";
    private String createTableProduct =
            "CREATE TABLE Product(idProduct int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, idProvider int FOREIGN KEY REFERENCES Provider(idProvider), productName varchar(30), productDescription varchar(500), price double)";

    private static PreparedStatement addProductStmt;
    private static PreparedStatement deleteProductStmt;
    private static PreparedStatement updateProductStmt;
    private static PreparedStatement getAllProductsStmt;
    private static PreparedStatement getAllProvidersByProductStmt;
    private static PreparedStatement deleteAllProductsByProviderStmt;
    private Statement stmt;

    public ProductManager() {
        try {
            conn = DriverManager.getConnection(url);
            stmt = conn.createStatement();

            ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()){
                if("Product".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                stmt.executeUpdate(createTableProduct);

            addProductStmt = conn.prepareStatement("INSERT INTO Product(idProvider, productName, productDescription, price) VALUES (?, ?, ?, ?)");
            deleteProductStmt = conn.prepareStatement("DELETE FROM Product WHERE idProduct=?");
            updateProductStmt = conn.prepareStatement("UPDATE Product SET productName = ?, productDescription = ?, price = ? WHERE idProduct = ?");
            getAllProductsStmt = conn.prepareStatement("SELECT idProduct, idProvider, productName, productDescription, price FROM Product");
            getAllProvidersByProductStmt = conn.prepareStatement("SELECT idProvider, providerName FROM Provider WHERE idProduct = ?");
            deleteAllProductsByProviderStmt = conn.prepareStatement("DELETE FROM Products WHERE idProvider = ?");
        } catch (SQLException e){
            e.printStackTrace();
        }
    }

    public Connection getConn() { return conn; }

    public int addProduct(Product p){
        int count = 0;
        try {
            addProductStmt.setInt(1, p.getIdProvider());
            addProductStmt.setString(2, p.getProductName());
            addProductStmt.setString(3, p.getProductDescription());
            addProductStmt.setDouble(4, p.getPrice());

            count = addProductStmt.executeUpdate();
        } catch (SQLException e){
            e.printStackTrace();
        }
        return count;
    }

    public void deleteProduct(int idProduct){
        try {
            deleteProductStmt.setInt(1, idProduct);
            deleteProductStmt.executeUpdate();
        } catch (SQLException e){
            e.printStackTrace();
        }
    }

    public List<Product> getAllProducts() {
        List<Product> productList = new ArrayList<Product>();

        try {
            ResultSet rs = getAllProductsStmt.executeQuery();

            while (rs.next()) {
                Product product = new Product();
                product.setIdProduct(rs.getInt("idProduct"));
                product.setIdProvider(rs.getInt("idProvider"));
                product.setProductName(rs.getString("productName"));
                product.setProductDescription(rs.getString("productDescription"));
                product.setPrice(rs.getDouble("price"));
                productList.add(product);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return productList;
    }

    public int updateProduct(Product product){
        int count = 0;
        try {
            updateProductStmt.setString(1, product.getProductName());
            updateProductStmt.setString(2, product.getProductDescription());
            updateProductStmt.setDouble(3, product.getPrice());
            updateProductStmt.setInt(4, product.getIdProduct());

            count = updateProductStmt.executeUpdate();
        } catch (SQLException e){
            e.printStackTrace();
        }
        return count;
    }

    public List<Provider> getAllProvidersByProducts(Product p){
        List<Provider> providerList = new ArrayList<Provider>();

        try {
            getAllProvidersByProductStmt.setInt(1, p.getIdProvider());
            ResultSet rs = getAllProductsStmt.executeQuery();

            while(rs.next()){
                Provider provider = new Provider();
                provider.setIdProvider(rs.getInt("idProvider"));
                provider.setProviderName(rs.getString("providerName"));
                providerList.add(provider);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        return providerList;
    }

    public int deleteAllProductsByProvider(Provider p){
        int count = 0;
        try{
            deleteAllProductsByProviderStmt.setInt(1, p.getIdProvider());
            count = deleteAllProductsByProviderStmt.executeUpdate();
        }catch (SQLException e){
            e.printStackTrace();
        }
        return count;
    }
}
